# Generated by Django 5.1.4 on 2025-01-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя покупателя')),
                ('instagram', models.CharField(max_length=50, verbose_name='Instagram покупателя')),
                ('phone', models.IntegerField(blank=True, max_length=13, verbose_name='Номер покупателя')),
                ('adress', models.CharField(blank=True, max_length=100, verbose_name='Адрес покупателя')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
