# Generated by Django 5.1.4 on 2025-01-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='Номер покупателя'),
        ),
    ]
