# Generated by Django 5.1.4 on 2025-02-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя покупателя'),
            preserve_default=False,
        ),
    ]
