# Generated by Django 5.1.4 on 2025-02-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigories',
            name='image_id',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Изображение'),
        ),
    ]
