# Generated by Django 5.1.4 on 2025-02-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_catigories_image_id_alter_product_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catigories',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_id',
        ),
        migrations.AddField(
            model_name='catigories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
