# Generated by Django 5.1.4 on 2025-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
