# Generated by Django 5.1.4 on 2025-01-04 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_catigories_image_id_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.catigories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
