# Generated by Django 5.1.4 on 2025-01-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_catigories_image_id_alter_catigories_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catigories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
